### PR TITLE
Bone app

### PR DESCRIPTION
**Pull request by shekhardw**
[FEA] Bone Segmentation App #198

First version of CT bone segmentation algorithm.

### CODE REVIEW

**Comment by MMelQin** [comment]
Please run auto style fixes: ./run check --autofix

BTW, expanding the details of the build/test to see the failures, and also checking the version of the checkers (a few) are the same in dev env; it happened to me that the out of sync versions caused to do quite a number of commit to correct the styling complaints.

**Comment by vikashg** [comment]
Hi @shekhardw. So, I see that you are using [clcat] (https://pypi.org/project/clcat/). Initially I had no idea about clcat so good to see that there is a clara toolkit. So, I tried installing once 
```
gupta@DIGI1036734:/data/Vikash/Tools/monai_deploy_new/monai-deploy-app-sdk/examples/apps/ct_bone_seg_app$ pip install clcat
Collecting clcat
  Downloading clcat-0.0.3-cp38-cp38-manylinux1_x86_64.whl (196 kB)
     |████████████████████████████████| 196 kB 88 kB/s 
Collecting patchelf
  Downloading patchelf-0.14.5.0-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.musllinux_1_1_x86_64.whl (326 kB)
     |████████████████████████████████| 326 kB 102 kB/s 
Installing collected packages: patchelf, clcat
Successfully installed clcat-0.0.3 patchelf-0.14.5.0
gupta@DIGI1036734:/data/Vikash/Tools/monai_deploy_new/monai-deploy-app-sdk/examples/apps/ct_bone_seg_app$ ls
```
However, when I tried to install the same inside a conda environment, I cannot install it 
```(base) gupta@DIGI1036734:/data/Vikash/Tools/monai_deploy_new/monai-deploy-app-sdk/examples/apps/ct_bone_seg_app$ pip install clcat
ERROR: Could not find a version that satisfies the requirement clcat (from versions: none)
ERROR: No matching distribution found for clcat
(base) gupta@DIGI1036734:/data/Vikash/Tools/monai_deploy_new/monai-deploy-app-sdk/examples/apps/ct_bone_seg_app$ 
```
Can you please look into this. 
In addition, I was wondering if the bone segmentation app should also be something like [the spleen segmentation app](https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/main/examples/apps/ai_spleen_seg_app/spleen_seg_operator.py). 
Another question are the bone segmentation model embeded in ```clcat``` ?

**Comment by vikashg** [comment]
@shekhardw Sounds good. If the clcat can be installed I can proceed with further testing. Let me know if you need more information to track down that error.

**Comment by vikashg** [comment]
@shekhardw Do we have any updates on this? Specifically clcat ?

**Comment by shekhardw** [comment]
@vikashg This work is on hold due to other high priority items. @rahul-imaging can share his thoughts.

**Comment by MMelQin** [comment]
With all indications this PR would not be finalized. Closing it now.

**Pull request closed without merging**
