### PR TITLE
Create aws_healthimaging.md

### PR DESCRIPTION
**Pull request by flamingofugang**
This is a new platform on AWS using MONAI deploy with native services like AWS HealthImaging and Amazon SageMaker

### CODE REVIEW

**Review by dbericat — CHANGES_REQUESTED** [review]
So great to finally see this! :) 

Please:

1. Add a folder aws_healthlakeimaging and move .md there
2. add architecture diagram to the md (same as in your aws-samples.
3. Please add link to MONAI Application Package (MAP) to https://github.com/Project-MONAI/monai-deploy/blob/main/guidelines/monai-application-package.md

**Comment by MMelQin** [comment]
@flamingofugang Hi Steve, thanks for the pull request. There is one important piece information that I'd need to share with you. A new App SDK version, 0.6.0, is about to be released. This version introduces breaking changes. So, in order to keep the AWS HealthImaging Jupyter notebooks working, instead of `pip install --upgrade -q "monai" "monai-deploy-app-sdk"`, we'd actually need to ping the App SDK version to ~=0.5.1. We'll consider update the code once v0.6.0 is released.

**Review by MMelQin — COMMENTED** [review]
Looks good! Thanks.

**Comment by MMelQin** [comment]
@flamingofugang Hi Steve, please sign off per [DCO ](https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/449/checks?check_run_id=16277928592)check suggests. I can help merge the PR once the contribution is attributed to you with you signing off the PR.

**Review by MMelQin — APPROVED** [review]

**Pull request merged**
