### PR TITLE
Fixed minor dependencies for fresh deployment

### PR DESCRIPTION
**Pull request by vikashg**
Here are some changes and dependencies that needs to be added to make the 03_segmentation_app and 04_mis_tutorial notebooks work.

### CODE REVIEW

**Review by MMelQin — APPROVED** [review]
Thanks for the fixes!

**Comment by gigony** [comment]
@vikashg Please commit with signature to pass `DCO` requirement.

See https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/208/checks?check_run_id=4317364632

**Review by gigony — APPROVED** [review]
Looks good to me.

**Comment by gigony** [comment]
Thanks @vikashg for the change!

**Pull request merged**
