### PR TITLE
Remove MONAI user ownership on MAP folders

### PR DESCRIPTION
**Pull request by KavinKrishnan**
Removing fixed `monai` user/privilege's on application package image

### CODE REVIEW

**Review by slbryson — APPROVED** [review]
Agreed on the approach.

**Comment by gigony** [comment]
@KavinKrishnan
Could you please sign this commit and update the description of this PR saying the context of this PR?

I wonder to what extent does this PR solves the issue described in https://github.com/Project-MONAI/monai-deploy-app-sdk/issues/202?

**Comment by KavinKrishnan** [comment]
> @KavinKrishnan Could you please sign this commit and update the description of this PR saying the context of this PR?
> 
> I wonder to what extent does this PR solves the issue described in #202?
> 
> Do we just want to run the container as root with this PR?

Yes, and think it is ok. It seems to be a bigger issue having the packager fix permissions in the image around one user `monai`. 

In a future MR, we could provide a way for the user to decide the user when packaging the image. However in the meantime, allowing them to run the container should suffice.

I think the alternative you suggested with a told `gosu` and making each user a super user may not be the best practice.

**Comment by MMelQin** [comment]
Generally for application security, especially FS access controls, use a group to grant permissions to the resources, and on deployment and at runtime, a specific service account just needs to be in this defined group. The application package does not need to pin down the specific user, which is a deployment/runtime concern.

Application understands the required permission or ACL the application specific resources (Docker image files etc, and the mapped folder on host), what specific group, and service account, to use is more the deployment platform configuration concern, to ensure the service account has the required permissions to the resources, without being granted elevated privilege.

**Comment by whoisj** [comment]
LGTM :shipit:

**Review by whoisj — APPROVED** [review]

**Comment by MMelQin** [comment]
Merge this PR for now, with the understanding of having #202 to address the account and permission issue.

**Pull request merged**
