### PR TITLE
Added option for SimpleInferer 

### PR DESCRIPTION
**Pull request by vikashg**
Added an option for SimpleInferer on monai_seg_inference_operator.py

### CODE REVIEW

**Comment by vikashg** [comment]
@MMelQin Including `StrEnum` gives me an error for testing. If you can have a look that will be really helpful. Maybe I am using it wrong.

**Comment by MMelQin** [comment]
> @MMelQin Including `StrEnum` gives me an error for testing. If you can have a look that will be really helpful. Maybe I am using it wrong.

Yes, needs to define the class of type StrEnum before using it. Will suggest some code.

**Comment by vikashg** [comment]
Hi @MMelQin,
So I looked up `Enum` which is similar to `StrEnum`. There are existing examples like 
image

But I don't know how this will help or enhance the existing code. Please let me know and I will fix it. 
Thanks 
Vikash

**Comment by MMelQin** [comment]
> Hi @MMelQin, So I looked up `Enum` which is similar to `StrEnum`. There are existing examples like image
> 
> But I don't know how this will help or enhance the existing code. Please let me know and I will fix it. Thanks Vikash

Another issue is that the MD App SDK requires Python version >= 3.7, for which the StrEnum is NOT available. This is why MONAI Core had [its impl of StrEnum](https://github.com/Project-MONAI/MONAI/blob/f355d1fc38c50e83e4f20ffe870c19a5814dc501/monai/utils/enums.py#L65), as Eric mentioned. For the upcoming version of the SDK, v0.6, I've changed to min version of Python >=3.8, but for 0.5 and any patch release of it, it is better to still stay with Python >=3.7. 

For our use case, the relevant magic strings had not been used in the App SDK or app code, I think we can safely use Enum or IntEnum for now.

**Review by MMelQin — COMMENTED** [review]
LGTM

**Review by MMelQin — APPROVED** [review]

**Pull request merged**
